repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=400"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.0
    hooks:
      - id: ruff-format
        args: [--check]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.1.0"
    hooks:
      - id: ruff
        files: "^src"
